spring.application.name=Icentric
spring.datasource.url=jdbc:postgresql://localhost:5432/aisafe
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.schemas=system
spring.flyway.locations=classpath:db/migration/system
logging.level.org.flywaydb=INFO
